### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by olifre** [nalabdou/Symfony-super-console#2]
I'd love to add this very useful extension to the Open-VSX marketplace:
https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace
so it can be used with VS Codium and FOSS editors. 

However, that requires the project to use an OSI license. Your other projects (e.g. `Symfony-code-snippets`) seem to already specify a license, but it is missing here. Can you specify the license in the repository? 
Of course, bonus points if you add it to Open-VSX yourself, otherwise I'd follow the approach to add it to https://github.com/open-vsx/publish-extensions :-). 

Thanks! :-)

**Comment by nalabdou** [comment]
https://github.com/nalabdou/Symfony-super-console/blob/master/LICENSE
